# Generated by Django 2.2.3 on 2020-01-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200113_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teampokemon',
            old_name='name',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
